### ISSUE TITLE
Thanks for sharing this! issue with Braktooth setup!

### ISSUE THREAD

**Issue by nosed07** [darkmentorllc/Blue2thprinting#3]
Hello,

I am trying to setup Braktooth from their repo, and sadly I am unable to download this file [wdissector.tar.zst](https://github.com/Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks/blob/master/wdissector.tar.zst)
Since that file is missing, not much to do with Braktooth really, I am kind of blocked there, although I have sweyntooth up and running.
Any chance you could make wdissector.tar.zst file available for download if you have it?

Thanks

**Comment by XenoKovah** [comment]
I recall having some problem like that too when I first set up braktooth. I think it has to do with the fact that it's too big a file for their git repo because they're not using LFS correctly or something like that. (Or it might have to do with the costs that github charges for LFS?). But I believe you can get the file from the artifact releases section of their git repo here: https://github.com/Matheus-Garbelini/braktooth_esp32_bluetooth_classic_attacks/releases/tag/v1.0.1. I see the ~400MB file in that zip file.

**Comment by nosed07** [comment]
Thanks a lot for your help! You can close this!
BTW congrats for opensecuritytraining2. I find it very interesting and userful.
